name:                raft-hs
version:             0.1.0.0
github:              "githubuser/raft-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/raft-hs#readme>

dependencies:
- base >= 4.7 && < 5
- acid-state ==0.16.0.1
- tomland ==1.3.3.0
- text ==1.2.4.1
- mtl ==2.2.2
- safecopy ==0.10.4.2
- containers ==0.6.2.1
- bytestring ==0.10.12.0
- serialise ==0.2.3.0
- optparse-applicative ==0.16.1.0
- scotty ==0.12
- wai-extra ==3.1.6
- stm ==2.5.0.0
- data-default ==0.7.1.1
- data-default-class ==0.1.2.0
library:
  source-dirs: src

executables:
  raft-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft-hs

tests:
  raft-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft-hs
